//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// </summary>
        internal static string _2015_1_Input {
            get {
                return ResourceManager.GetString("2015.1.Input", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string _2015_2_Input {
            get {
                return ResourceManager.GetString("2015.2.Input", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string _2015_3_Input {
            get {
                return ResourceManager.GetString("2015.3.Input", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string _2024_1_Input {
            get {
                return ResourceManager.GetString("2024.1.Input", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string _2024_2_Input {
            get {
                return ResourceManager.GetString("2024.2.Input", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string _2024_3_Input {
            get {
                return ResourceManager.GetString("2024.3.Input", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string _2024_4_Input {
            get {
                return ResourceManager.GetString("2024.4.Input", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string _2024_4_Synopsis {
            get {
                return ResourceManager.GetString("2024.4.Synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string _2024_5_Input {
            get {
                return ResourceManager.GetString("2024.5.Input", resourceCulture);
            }
        }
        internal static string _2024_5_Test_Input {
            get {
                return ResourceManager.GetString("2024.5.Test.Input", resourceCulture);
            }
        }
        internal static string _2024_6_Input {
            get {
                return ResourceManager.GetString("2024.6.Input", resourceCulture);
            }
        }
    }
}
